### ISSUE TITLE
Error when downloading any blender release

### ISSUE THREAD

**Issue by hcraT** [AlexChaplinBraz/BlenderLauncher#4]
Hi,
when I install a blender release with version 0.4.0 I get the following error:
```
GUI install error at src/gui/install.rs:301, which was:
Custom {
    kind: NotFound,
    error: TarError {
        desc: "failed to create `/home/myuser/.cache/ablavema/blender-3.0.0-beta+v30.f71813204c40-linux.x86_64-release/blender-3.0.0-beta+v30.f71813204c40-linux.x86_64-release`",
        io: Custom {
            kind: NotFound,
            error: "No such file or directory (os error 2) while canonicalizing /home/myuser/.cache/ablavema/blender-3.0.0-beta+v30.f71813204c40-linux.x86_64-release",
        },
    },
}
```

I ran git bisect to identify the commit where the problem was introduced and the result is:
```
66a24b4d3c8aeea3d75fd1d8ec2eaf77cfd80807 is the first bad commit
commit 66a24b4d3c8aeea3d75fd1d8ec2eaf77cfd80807
Author: Alexander Chaplin Braz <contact@alexchaplinbraz.com>
Date:   Wed Nov 3 17:26:12 2021 +0100

    Update dependencies

 Cargo.lock | 715 +++++++++++++++++++++++++++++++++++--------------------------
 Cargo.toml |   2 +-
 build.rs   |   7 +-
 3 files changed, 419 insertions(+), 305 deletions(-)
```

I've checked which packages were updated and given the error above the most logical was the `tar` package. I then tried to rebuild the program with the old version (i.e. v0.4.35) and it works. I tried tar v0.4.36 and the program fails with that version as well. By checking the commit log for the tar package it seems that [this commit](https://github.com/alexcrichton/tar-rs/commit/d90a02f582c03dfa0fd11c78d608d0974625ae5d) could be causing the problem. I don't have any experience with rust and so I don't know how to fix this problem.

I hope the information I've included above is sufficient to solve this issue.

Thank you.

**Comment by AlexChaplinBraz** [comment]
Damn, that was quite thorough of you, thanks. I'm looking into it.

**Comment by AlexChaplinBraz** [comment]
Alright. Basically, I was relying on `tar` to create the initial extraction directory, but after that commit, `tar` no longer creates it. So I just needed to create it myself, and 45d964d seems to fix it.

Guess I'll release a `0.4.1` with just that since it affects every package. I would've caught this error if only I didn't rush to publish `0.4.0` within that week... And I was 4 minutes late anyway. Lesson learned.

**Comment by hcraT** [comment]
I tested the new release and it works correctly.

Sometimes we need to screw up to learn :) Cool release name BTW.
